# [ id [uint8], point [x [m], y [m], z [m]] ]
points:
    0

# [ id [uint8], orientation [roll [deg], pitch [deg], yaw [deg]] ]
orientations:
    0

# [ id [uint8], pose [x [m], y [m], z [m], roll [deg], pitch [deg], yaw [deg]] ]
poses:
    - [1,  [-2.5,  2.0, .NaN, .NaN, .NaN,   0.0] ]
    - [2,  [-1.5,  2.0, .NaN, .NaN, .NaN,   0.0] ]
    - [3,  [-0.5,  2.0, .NaN, .NaN, .NaN,   0.0] ]
    - [4,  [ 0.5,  2.0, .NaN, .NaN, .NaN,   0.0] ]
    - [5,  [ 1.5,  2.0, .NaN, .NaN, .NaN,   0.0] ]
    - [6,  [ 2.5,  2.0, .NaN, .NaN, .NaN,   0.0] ]
    - [7,  [ 2.5,  2.0, .NaN, .NaN, .NaN, 180.0] ]
    - [8,  [ 1.5,  2.0, .NaN, .NaN, .NaN, 180.0] ]
    - [9,  [ 0.5,  2.0, .NaN, .NaN, .NaN, 180.0] ]
    - [10, [-0.5,  2.0, .NaN, .NaN, .NaN, 180.0] ]
    - [11, [-1.5,  1.0, .NaN, .NaN, .NaN, 270.0] ]
    - [12, [-0.5,  0.0, .NaN, .NaN, .NaN,   0.0] ]
    - [13, [ 0.5,  0.0, .NaN, .NaN, .NaN,   0.0] ]
    - [14, [ 2.5,  2.0, .NaN, .NaN, .NaN,  90.0] ]
    - [15, [ 0.5,  4.0, .NaN, .NaN, .NaN, 180.0] ]
    - [16, [-1.5,  2.0, .NaN, .NaN, .NaN, 270.0] ]
    - [17, [ 0.5,  0.0, .NaN, .NaN, .NaN,   0.0] ]
    - [18, [ 1.5,  0.0, .NaN, .NaN, .NaN,   0.0] ]
    - [19, [ 3.0, -1.5, .NaN, .NaN, .NaN, 270.0] ]
    - [20, [ 3.0, -2.5, .NaN, .NaN, .NaN, 270.0] ]
    - [21, [ 1.5, -3.5, .NaN, .NaN, .NaN, 180.0] ]
    - [22, [ 0.5, -3.5, .NaN, .NaN, .NaN, 180.0] ]
    - [23, [-0.5, -3.5, .NaN, .NaN, .NaN, 180.0] ]
    - [24, [-1.5, -3.5, .NaN, .NaN, .NaN, 180.0] ]
    - [25, [-2.5, -3.5, .NaN, .NaN, .NaN, 180.0] ]
    - [26, [-3.5, -3.5, .NaN, .NaN, .NaN, 180.0] ]
    - [27, [-4.0, -2.5, .NaN, .NaN, .NaN,  90.0] ]
    - [28, [-4.0, -1.5, .NaN, .NaN, .NaN,  90.0] ]
    - [29, [-4.0, -0.5, .NaN, .NaN, .NaN,  90.0] ]
    - [30, [-4.0,  0.5, .NaN, .NaN, .NaN,  90.0] ]
    - [31, [-4.0,  1.5, .NaN, .NaN, .NaN,  90.0] ]
    - [32, [-4.0,  2.5, .NaN, .NaN, .NaN,  90.0] ]
    - [33, [-4.0,  3.5, .NaN, .NaN, .NaN,  90.0] ]
    - [34, [-2.5,  5.0, .NaN, .NaN, .NaN,   0.0] ]
    - [35, [-1.5,  5.0, .NaN, .NaN, .NaN,   0.0] ]
    - [36, [-0.5,  5.0, .NaN, .NaN, .NaN,   0.0] ]
    - [37, [ 0.5,  5.0, .NaN, .NaN, .NaN,   0.0] ]
    - [38, [ 1.5,  5.0, .NaN, .NaN, .NaN,   0.0] ]
    - [39, [ 2.5,  5.0, .NaN, .NaN, .NaN,   0.0] ]
    - [40, [ 2.5,  4.0, .NaN, .NaN, .NaN, 180.0] ]
    - [41, [ 1.5,  4.0, .NaN, .NaN, .NaN, 180.0] ]
    - [42, [ 0.5,  4.0, .NaN, .NaN, .NaN, 180.0] ]
    - [43, [-0.5,  4.0, .NaN, .NaN, .NaN, 180.0] ]
    - [44, [-1.5,  4.0, .NaN, .NaN, .NaN, 180.0] ]
    - [45, [-2.5,  4.0, .NaN, .NaN, .NaN, 180.0] ]
    - [46, [-3.5,  3.0, .NaN, .NaN, .NaN, 270.0] ]
    - [47, [-2.5,  2.0, .NaN, .NaN, .NaN,   0.0] ]

# [ id [uint8], ? [needs to be defined] ]
actions:
    0
