# configuration file for driving the TurtleBot2 with its odometry and the Qualisys system

# file to load coordinates/poses from. 
# HAS to be in ~/catkin_ws/src/scripts/config/
evaluation_specification_file: evaluation_specification.yaml

# sets topic for controller
# has to be a nav_msgs.msg Odometry message
# /odometry/filtered for EKF odom topic
# /odom for TB2 odometry
# /qualisys/<rigid_body_name>/odom for Qualisys localization
localization_topic: /odometry/filtered

# set maximum velocity
# 0.3 [m/s], max. linear velocity of turtlebot2/kobuki
# 3.14 [rad/s], max. rotational velocity of turtlebot2/kobuki
# v_max_lin = 0.3 and v_max_ang = 1.0 work well for simulation with TB2
v_max_lin: 0.3
v_max_ang: 1.0

# decides how accurate you want the robot to be
# in [m] and [rad]
# 0.17 [rad] = 10 deg
accuracy_dist: 0.1
accuracy_ang: 0.17

# P-gain (proportional gain) of velocities
# velocities get calculated by distance of goal
K_vel_lin: 1
K_vel_ang: 1
K_vel_rot: 1.5 # rotating on the spot is too slow if K = 1

# decides what information get displayed by logging
# supported: INFO, DEBUG
verbosity_level: INFO

######## NOT IMPLEMENTED YET
######## Please set in .launch file
# topics you want to record in the .bag file
# ros_bag: topics

######## NOT IMPLEMENTED YET
######## Please set odom0 in .launch file
# model you want to track
# please only specify the <mocap_model> in /qualisys/<mocap_model>/odom
# mobile_base for TurtleBot2 in Gazebo, 
# rigid body name of QTM (e.g. RB_TB) during real life measurement
# mocap_model: /qualisys/mobile_base/odom