# configuration file for driving the TurtleBot2 with its odometry and the Qualisys system

# file to load coordinates/poses from. 
# HAS to be in ~/catkin_ws/src/scripts/config/
evaluation_specification_file: evaluation_specification.yaml

# decides what information get displayed
# supported: INFO, DEBUG
log_level: info, debug

# model you want to track
# mobile_base for TurtleBot2 in Gazebo, 
# during real life measurement the name of your rigid body (e.g. RB_TB)
mocap_model: RB_TB

# set maximum velocity
# 0.3 [m/s], max. linear velocity of turtlebot2/kobuki
# 3.14 [rad/s], max. rotational velocity of turtlebot2/kobuki
mav_vel_lin: 0.3
max_vel_ang: 3.14

# decides how accurate you want the robot to be
# in [m] and [rad]
# 0.17 [rad] = 0.1° 
accuracy_dist: 0.1
accuracy_ang: 0.17

# P-gain of velocities
# velocities get calculated by distance of goal
K_vel_lin: 1
K_vel_ang: 1

# topics you want to record in the .bag file
ros_bag: topics